# -*- coding: utf-8 -*-
"""Github test code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bEY64rSTemhHO5Hknp7Y_WHVXc0NpIT1
"""

'''money =  5223.255
account = 3
print('I have money {1:,.2f} baht\nI have in wallet {0:,d}'.format(money, account))'''

